### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by KarelWintersky** [guitmz/fasm-docker#1]
Pls, add dockerfile to dockerhub

**Comment by guitmz** [comment]
@KarelWintersky hey its already available in Docker Hub since the 1st day.

Here: https://hub.docker.com/r/guitmz/fasm/

Do you have any problems pulling this image?

**Comment by KarelWintersky** [comment]
It is available at dockerhub, but dockerfile is NOT visible there.

It is a bad practice.

**Comment by KarelWintersky** [comment]
No problems with pulling.

Only a valid paranoia

**Comment by guitmz** [comment]
@KarelWintersky ah thats true, sorry! I will fix it :) thanks for reminding me

**Comment by guitmz** [comment]
Done: https://hub.docker.com/r/guitmz/fasm/
